-- Seed standard questions (115 questions)
INSERT INTO game_questions (question, answer, category) VALUES
  ('How many sides does a triangle have?', 3, 'standard'),
  ('How many colors are in a standard traffic light?', 3, 'standard'),
  ('How many continents are there in the world?', 7, 'standard'),
  ('How many days are there in a week?', 7, 'standard'),
  ('How many legs does a spider have?', 8, 'standard'),
  ('How many players on a basketball team on the court?', 5, 'standard'),
  ('How many strings does a standard guitar have?', 6, 'standard'),
  ('How many years are in a decade?', 10, 'standard'),
  ('How many sides does a hexagon have?', 6, 'standard'),
  ('How many planets are recognized in our solar system?', 8, 'standard'),
  ('How many months have 28 days?', 12, 'standard'),
  ('How many hours are in a day?', 24, 'standard'),
  ('How many vowels are in the English alphabet?', 5, 'standard'),
  ('How many letters are in the word ''cat''?', 3, 'standard'),
  ('How many seasons are there in a year?', 4, 'standard'),
  ('How many fingers on one hand?', 5, 'standard'),
  ('How many toes on one foot?', 5, 'standard'),
  ('How many sides does a square have?', 4, 'standard'),
  ('How many corners does a rectangle have?', 4, 'standard'),
  ('How many wheels are on a tricycle?', 3, 'standard'),
  ('How many months are in a year?', 12, 'standard'),
  ('How many days are in a weekend?', 2, 'standard'),
  ('How many letters are in the word ''dog''?', 3, 'standard'),
  ('How many primary colors are in light (RGB)?', 3, 'standard'),
  ('How many primary colors are in paint (RYB)?', 3, 'standard'),
  ('How many points does a triangle have?', 3, 'standard'),
  ('How many sides does a rectangle have?', 4, 'standard'),
  ('How many even numbers are between 1 and 5 (exclusive)?', 2, 'standard'),
  ('How many eyes does a typical human have?', 2, 'standard'),
  ('How many ears does a typical human have?', 2, 'standard'),
  ('How many primary compass directions are there?', 4, 'standard'),
  ('How many quarters make a dollar?', 4, 'standard'),
  ('How many seasons are in ''The Four Seasons''?', 4, 'standard'),
  ('How many legs does a cat have?', 4, 'standard'),
  ('How many letters are in the word ''sun''?', 3, 'standard'),
  ('How many letters are in the word ''moon''?', 4, 'standard'),
  ('How many days are in February in a non-leap year?', 28, 'standard'),
  ('How many days are in February in a leap year?', 29, 'standard'),
  ('How many corners does a triangle have?', 3, 'standard'),
  ('How many sides does a pentagon have?', 5, 'standard'),
  ('How many sides does an octagon have?', 8, 'standard'),
  ('How many colors are in a rainbow?', 7, 'standard'),
  ('How many letters are in the word ''apple''?', 5, 'standard'),
  ('How many letters are in the word ''hello''?', 5, 'standard'),
  ('How many minutes are in half an hour?', 30, 'standard'),
  ('How many lines are in a haiku?', 3, 'standard'),
  ('How many strikes make an out in baseball?', 3, 'standard'),
  ('How many points is a field goal worth in American football?', 3, 'standard'),
  ('How many Great Lakes are there?', 5, 'standard'),
  ('How many players are on a soccer team on the field?', 11, 'standard'),
  ('How many players are on a baseball team on the field?', 9, 'standard'),
  ('How many months have 30 days?', 4, 'standard'),
  ('How many prime numbers are less than 20?', 8, 'standard'),
  ('How many letters are in the Greek alphabet?', 24, 'standard'),
  ('How many edges does a cube have?', 12, 'standard'),
  ('How many faces does a cube have?', 6, 'standard'),
  ('How many vertices does a cube have?', 8, 'standard'),
  ('How many sides does a dodecagon have?', 12, 'standard'),
  ('How many zodiac signs are there?', 12, 'standard'),
  ('How many hours are on a standard analog clock face?', 12, 'standard'),
  ('How many pawns does each player have in chess?', 8, 'standard'),
  ('How many squares are on one side of a chessboard?', 8, 'standard'),
  ('How many provinces are in Canada?', 10, 'standard'),
  ('How many amendments are in the U.S. Bill of Rights?', 10, 'standard'),
  ('How many gas giant planets are in our solar system?', 4, 'standard'),
  ('How many strings does a violin have?', 4, 'standard'),
  ('How many symphonies did Beethoven compose?', 9, 'standard'),
  ('How many keys are in a musical octave (Western)?', 12, 'standard'),
  ('How many cranial nerves are there?', 12, 'standard'),
  ('How many carpal bones are in one human wrist?', 8, 'standard'),
  ('How many colors are on the flag of the United States?', 3, 'standard'),
  ('How many stripes are on the flag of the United States?', 13, 'standard'),
  ('How many original American colonies were there?', 13, 'standard'),
  ('How many amendments does the U.S. Constitution have?', 27, 'standard'),
  ('How many member countries are in the European Union (2024)?', 27, 'standard'),
  ('How many letters are in the English alphabet?', 26, 'standard'),
  ('How many Olympic rings are there?', 5, 'standard'),
  ('How many continents border the Atlantic Ocean?', 4, 'standard'),
  ('How many bones are in the human middle and inner ear (ossicles)?', 6, 'standard'),
  ('How many sides does a heptagon have?', 7, 'standard'),
  ('How many protons are in a carbon atom?', 6, 'standard'),
  ('How many SI base units are there?', 7, 'standard'),
  ('How many Wonders of the Ancient World were there?', 7, 'standard'),
  ('How many traditional lunar phases are named?', 8, 'standard'),
  ('How many players are on a rugby union team on the field?', 15, 'standard'),
  ('How many lines are in a Shakespearean sonnet?', 14, 'standard'),
  ('How many Nobel Prize categories are awarded each year?', 6, 'standard'),
  ('How many official languages does the United Nations have?', 6, 'standard'),
  ('How many cervical vertebrae are in the human neck?', 7, 'standard'),
  ('How many planets were known to ancient astronomers?', 5, 'standard'),
  ('How many Pandava brothers are in the Mahabharata?', 5, 'standard'),
  ('How many books are in the Pentateuch?', 5, 'standard'),
  ('How many Gospels are in the New Testament?', 4, 'standard'),
  ('How many letters are in the Hebrew alphabet?', 22, 'standard'),
  ('How many letters are in the Arabic alphabet?', 28, 'standard'),
  ('How many major scales are there in Western music?', 12, 'standard'),
  ('How many teams are in a FIFA World Cup group?', 4, 'standard'),
  ('How many players are on a volleyball team on the court?', 6, 'standard'),
  ('How many squares are on a 4x4 grid?', 16, 'standard'),
  ('How many justices sit on the U.S. Supreme Court?', 9, 'standard'),
  ('How many apostles did Jesus have?', 12, 'standard'),
  ('How many labors did Hercules complete?', 12, 'standard'),
  ('How many animals are in the Chinese zodiac?', 12, 'standard'),
  ('How many events are in the Olympic decathlon?', 10, 'standard'),
  ('How many players are in a basketball starting lineup (one team)?', 5, 'standard'),
  ('How many cards are in a single suit in a standard deck?', 13, 'standard'),
  ('How many face cards are in a standard deck of cards?', 12, 'standard'),
  ('How many days are in September?', 30, 'standard'),
  ('How many minutes are in a quarter hour?', 15, 'standard'),
  ('How many semitones are in a perfect fifth?', 7, 'standard'),
  ('How many bones form the human thoracic vertebrae?', 12, 'standard'),
  ('How many edges does a regular tetrahedron have?', 6, 'standard'),
  ('How many faces does a regular octahedron have?', 8, 'standard'),
  ('How many corners (vertices) does a regular dodecahedron have?', 20, 'standard'),
  ('How many sides does a nonagon have?', 9, 'standard');

-- Seed hard questions (130 questions)
INSERT INTO game_questions (question, answer, category) VALUES
  ('How many times did the Chicago Bulls win the NBA Championship in the 1990s?', 6, 'hard'),
  ('How many studio albums did The Beatles release?', 13, 'hard'),
  ('How many bones are in the human wrist (carpal bones)?', 8, 'hard'),
  ('How many players are on a cricket team?', 11, 'hard'),
  ('How many cervical vertebrae do most mammals have?', 7, 'hard'),
  ('How many Academy Awards did ''Titanic'' (1997) win?', 11, 'hard'),
  ('How many hearts does an octopus have?', 3, 'hard'),
  ('How many stripes are on the American flag?', 13, 'hard'),
  ('How many Olympian gods reside on Mount Olympus in Greek mythology?', 12, 'hard'),
  ('How many pairs of ribs do humans have?', 12, 'hard'),
  ('How many semitones are in an octave?', 12, 'hard'),
  ('How many colonies originally formed the United States?', 13, 'hard'),
  ('How many face cards are in a standard suit of playing cards?', 3, 'hard'),
  ('How many provinces does Canada have?', 10, 'hard'),
  ('How many labors did Hercules perform?', 12, 'hard'),
  ('How many apostles did Jesus have?', 12, 'hard'),
  ('How many trials of Apollo are there in Rick Riordan''s series?', 5, 'hard'),
  ('How many times did Roger Federer win Wimbledon?', 8, 'hard'),
  ('How many symphonies did Beethoven complete?', 9, 'hard'),
  ('How many films are in the original Star Wars trilogy?', 3, 'hard'),
  ('How many time zones does Russia span?', 11, 'hard'),
  ('How many letters are in the Hawaiian alphabet?', 13, 'hard'),
  ('How many muses are there in Greek mythology?', 9, 'hard'),
  ('How many signs are in the Chinese zodiac?', 12, 'hard'),
  ('How many gates did ancient Thebes have according to Homer?', 7, 'hard'),
  ('How many hills was Rome built on?', 7, 'hard'),
  ('How many innings are in a regulation baseball game?', 9, 'hard'),
  ('How many players are on a field hockey team?', 11, 'hard'),
  ('How many novels are in the Chronicles of Narnia series?', 7, 'hard'),
  ('How many deadly sins are there in Christian tradition?', 7, 'hard'),
  ('How many dwarfs befriended Snow White?', 7, 'hard'),
  ('How many rings are in the Audi logo?', 4, 'hard'),
  ('How many justices serve on the U.S. Supreme Court?', 9, 'hard'),
  ('How many planets in our solar system have rings?', 4, 'hard'),
  ('How many fluid ounces are in a standard U.S. cup?', 8, 'hard'),
  ('How many bits are in a byte?', 8, 'hard'),
  ('How many strings does a standard ukulele have?', 4, 'hard'),
  ('How many tastes can the human tongue detect?', 5, 'hard'),
  ('How many Academy Awards did ''Ben-Hur'' (1959) win?', 11, 'hard'),
  ('How many points is a touchdown worth in American football?', 6, 'hard'),
  ('How many witches appear in the opening of Macbeth?', 3, 'hard'),
  ('How many noble gases are there?', 6, 'hard'),
  ('How many tentacles does a squid have?', 10, 'hard'),
  ('How many keys are in an octave on a piano (including black)?', 12, 'hard'),
  ('How many cards are dealt to each player in Texas Hold''em?', 2, 'hard'),
  ('How many stomachs does a cow have?', 4, 'hard'),
  ('How many Grand Slam tennis tournaments are there?', 4, 'hard'),
  ('How many herbs and spices are in KFC''s original recipe?', 11, 'hard'),
  ('How many points is a safety worth in American football?', 2, 'hard'),
  ('How many elements are in the first period of the periodic table?', 2, 'hard'),
  ('How many amendments are in the U.S. Bill of Rights?', 10, 'hard'),
  ('How many Academy Awards did ''The Lord of the Rings: Return of the King'' win?', 11, 'hard'),
  ('How many lanes are in an Olympic swimming pool?', 8, 'hard'),
  ('How many valves does a trumpet have?', 3, 'hard'),
  ('How many strings does a standard violin have?', 4, 'hard'),
  ('How many eyes does a bee have?', 5, 'hard'),
  ('How many points is the letter Q worth in Scrabble?', 10, 'hard'),
  ('How many countries border Switzerland?', 5, 'hard'),
  ('How many World Cups has Brazil won (men''s football)?', 5, 'hard'),
  ('How many hurdles are in a 110m hurdles race?', 10, 'hard'),
  ('How many stars are on the European Union flag?', 12, 'hard'),
  ('How many books are in the Torah?', 5, 'hard'),
  ('How many points does a Star of David have?', 6, 'hard'),
  ('How many tribes of Israel were there?', 12, 'hard'),
  ('How many feet are in a fathom?', 6, 'hard'),
  ('How many faces does a dodecahedron have?', 12, 'hard'),
  ('How many furlongs are in a mile?', 8, 'hard'),
  ('How many pillars of Islam are there?', 5, 'hard'),
  ('How many members were in the Fellowship of the Ring?', 9, 'hard'),
  ('How many notes are in a chromatic scale?', 12, 'hard'),
  ('How many points is a field goal worth in basketball?', 2, 'hard'),
  ('How many Harry Potter books are there?', 7, 'hard'),
  ('How many time zones does mainland China officially use?', 1, 'hard'),
  ('How many colors are in a rainbow according to Newton?', 7, 'hard'),
  ('How many edges does a cube have?', 12, 'hard'),
  ('How many countries does the equator pass through?', 13, 'hard'),
  ('How many countries border Germany?', 9, 'hard'),
  ('How many countries border France (in Europe)?', 8, 'hard'),
  ('How many players are on a volleyball team on the court?', 6, 'hard'),
  ('How many players are on an ice hockey team on the ice?', 6, 'hard'),
  ('How many protons does carbon have?', 6, 'hard'),
  ('How many original Ivy League universities are there?', 8, 'hard'),
  ('How many eyes does a spider typically have?', 8, 'hard'),
  ('How many legs does a lobster have?', 10, 'hard'),
  ('How many points is the letter X worth in Scrabble?', 8, 'hard'),
  ('How many vertices does a cube have?', 8, 'hard'),
  ('How many faces does an octahedron have?', 8, 'hard'),
  ('How many edges does a tetrahedron have?', 6, 'hard'),
  ('How many Academy Awards did ''West Side Story'' (1961) win?', 10, 'hard'),
  ('How many times did Michael Schumacher win the F1 World Championship?', 7, 'hard'),
  ('How many players are on a water polo team in the pool?', 7, 'hard'),
  ('How many countries are in the UK?', 4, 'hard'),
  ('How many countries are in Scandinavia (traditional definition)?', 3, 'hard'),
  ('How many countries are in the Nordic region?', 5, 'hard'),
  ('How many Great Lakes are there?', 5, 'hard'),
  ('How many permanent members are on the UN Security Council?', 5, 'hard'),
  ('How many piano concertos did Beethoven compose?', 5, 'hard'),
  ('How many Brandenburg Concertos did Bach compose?', 6, 'hard'),
  ('How many Crusades were there (traditionally numbered)?', 9, 'hard'),
  ('How many days did the Cuban Missile Crisis last?', 13, 'hard'),
  ('How many cards are dealt in a game of Blackjack initially?', 2, 'hard'),
  ('How many squares are in a row on a chess board?', 8, 'hard'),
  ('How many pawns does each player start with in chess?', 8, 'hard'),
  ('How many points is a converted try worth in rugby union?', 7, 'hard'),
  ('How many feet are in a yard?', 3, 'hard'),
  ('How many teaspoons are in a tablespoon?', 3, 'hard'),
  ('How many cups are in a quart?', 4, 'hard'),
  ('How many quarts are in a gallon?', 4, 'hard'),
  ('How many pints are in a quart?', 2, 'hard'),
  ('How many lobes does the human liver have?', 4, 'hard'),
  ('How many chambers does a human heart have?', 4, 'hard'),
  ('How many cervical nerves are there in the human body?', 8, 'hard'),
  ('How many lumbar vertebrae do humans have?', 5, 'hard'),
  ('How many bones are in the human middle ear?', 3, 'hard'),
  ('How many taste buds regions are on the tongue (traditional model)?', 4, 'hard'),
  ('How many metatarsal bones are in each human foot?', 5, 'hard'),
  ('How many tarsal bones are in each human foot?', 7, 'hard'),
  ('How many phalanges are in each human thumb?', 2, 'hard'),
  ('How many novels did Jane Austen complete?', 6, 'hard'),
  ('How many strings does a standard bass guitar have?', 4, 'hard'),
  ('How many strings does a standard banjo have?', 5, 'hard'),
  ('How many valves does a French horn have?', 4, 'hard'),
  ('How many keys does a standard recorder have?', 7, 'hard'),
  ('How many players are on a doubles tennis team?', 2, 'hard'),
  ('How many players are on a beach volleyball team?', 2, 'hard'),
  ('How many periods are in an NHL hockey game?', 3, 'hard'),
  ('How many sets are needed to win a men''s Grand Slam tennis match?', 3, 'hard'),
  ('How many dots are on the opposite sides of a die?', 7, 'hard'),
  ('How many letters are in the word ''Mississippi'' that are unique?', 4, 'hard'),
  ('How many points is the black ball worth in snooker?', 7, 'hard');
